In [1]:
# Python exmaple of broadcasting
import numpy as np

A = np.array([[56,0,4.4,68],[1.2,104,52,8],[1.8,135,99,0.9]])

In [8]:
cal = A.sum(axis = 0)
# Broadcating where a (3,4) matrix is divided by a (1,4) matrix
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
# Broadcatsing example
print(np.array([1,2,3,4]) + 100)

[101 102 103 104]


In [13]:
# Broadcatsing example
a = np.array([[1,2,3],[4,5,6]])
b = np.array([100,200,300])
print(f'{a} + {b}')
print(f'= {a+b}')

[[1 2 3]
 [4 5 6]] + [100 200 300]
= [[101 202 303]
 [104 205 306]]


In [ ]:
# Broadcasting works for both column and row
# (m,n) op (1,m) or (m,1), the second matrix will be extended to (m,n)
# https://numpy.org/doc/stable/user/basics.broadcasting.html

In [29]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

(3, 3)